---
driver_plugin: vagrant
platforms:
- name: centos-6.3
  driver_config:
    box: centos63
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
  run_list:
  - recipe[httpd]
  - recipe[minitest-handler]
suites:
- name: default
  run_list: []
  attributes: {}
